apiVersion: v1
kind: Namespace
metadata:
  name: vsts
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: devops-service-user
  namespace: vsts
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: devops-service-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: devops-service-user
  namespace: vsts
