apiVersion: apps/v1
kind: Deployment
metadata:
  name: linux-web
spec:
  template:
    spec:
      containers:
        - name: linux-web
          env:
            - name: "ConfigOptions__ApplicationName"
              value: "My web app QA"
            - name: "ConfigOptions__Secret"
              valueFrom:
                secretKeyRef:
                  name: "qa-app-secrets"
                  key: "ConfigOptions__Secret"
